"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import { useEffect, useState } from "react";

const ThreeNetwork = dynamic(() => import("./ThreeNetwork"), { ssr: false });
const label = "text-[11px] font-bold tracking-[.14em] uppercase";
const section = "relative z-[1] border-b border-line bg-paper/80 px-[3vw] py-[110px] backdrop-blur-[2px] max-[800px]:px-[5vw] max-[800px]:py-[75px]";
const smallMeta = "block text-[9px] tracking-[.12em] text-muted uppercase";
const footer = "relative z-[2] bg-ink px-[3vw] pt-[90px] pb-[35px] text-paper max-[800px]:px-[5vw] max-[800px]:pt-[70px] max-[800px]:pb-[30px]";

function ScrollChoreography() {
  useEffect(() => {
    const root = document.documentElement;
    const reduced = matchMedia("(prefers-reduced-motion: reduce)").matches;
    const items = [...document.querySelectorAll<HTMLElement>(".scroll-reveal")];
    if (reduced) { items.forEach((item) => item.classList.add("in-view")); return; }
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => {
      if (entry.isIntersecting) { (entry.target as HTMLElement).classList.add("in-view"); observer.unobserve(entry.target); }
    }), { threshold: .14, rootMargin: "0px 0px -8%" });
    items.forEach((item) => observer.observe(item));
    let raf = 0;
    const update = () => { raf = 0; root.style.setProperty("--scroll-y", String(scrollY)); const max = document.documentElement.scrollHeight - innerHeight; const progress = max > 0 ? scrollY / max : 0; root.style.setProperty("--page-progress", String(progress)); root.style.setProperty("--scene-fade", String(.96 - progress * .72)); };
    const onScroll = () => { if (!raf) raf = requestAnimationFrame(update); };
    const onPointer = (event: PointerEvent) => { root.style.setProperty("--pointer-x", `${event.clientX}px`); root.style.setProperty("--pointer-y", `${event.clientY}px`); root.style.setProperty("--pointer-nx", String(event.clientX / innerWidth - .5)); root.style.setProperty("--pointer-ny", String(event.clientY / innerHeight - .5)); };
    update(); addEventListener("scroll", onScroll, { passive: true }); addEventListener("pointermove", onPointer, { passive: true });
    return () => { observer.disconnect(); removeEventListener("scroll", onScroll); removeEventListener("pointermove", onPointer); if (raf) cancelAnimationFrame(raf); };
  }, []);
  return <><div className="scroll-progress motion-atmosphere pointer-events-none fixed top-0 right-0 z-19 h-svh w-[3px] origin-top bg-acid max-[800px]:w-0.5" aria-hidden /><div className="scroll-orbit motion-atmosphere pointer-events-none fixed top-[32vh] -right-[18vw] -z-1 size-[36vw] rounded-full bg-[radial-gradient(circle,rgba(201,255,72,.14),rgba(201,255,72,0)_67%)] max-[800px]:-right-[38vw] max-[800px]:size-[70vw]" aria-hidden /><div className="cursor-atmosphere motion-atmosphere pointer-events-none fixed top-0 left-0 z-18 size-[170px] rounded-full bg-[radial-gradient(circle,rgba(201,255,72,.22),rgba(201,255,72,0)_68%)] opacity-35 mix-blend-multiply transition-[width,height,opacity] duration-300" aria-hidden /></>;
}

const projects = [
  { number: "01", title: "Morae", href: "/work/morae", eyebrow: "Platform evolution · Next.js + Craft CMS", intro: "Taking over a live legal-tech platform and evolving it without losing the knowledge embedded in its past.", detail: "I had worked on Morae when its website was still a monolithic WordPress build. After another company delivered its first WordPress-headless architecture with GraphQL, Apollo and Next.js, our team took over. I could read the inherited system in context, rebuild substantial parts of the frontend and progressively move content from WordPress to Craft CMS while both systems continued to coexist.", result: "Historical knowledge became delivery speed: data modelling, Craft architecture, GraphQL, React components, redirects and revalidation could move forward without destabilising the live platform." },
  { number: "02", title: "Shared multisite", href: "/work/shared-multisite", eyebrow: "Frontend systems · Multiple websites", intro: "A shared component system that lets related sites evolve consistently without forcing them to become identical.", detail: "Working inside an established multi-site codebase means understanding where consistency is valuable and where each website needs room to differ. The work combines reusable React architecture, CMS-driven variation and careful changes that do not create regressions across the wider platform.", result: "One senior developer who can reason across the system, isolate the impact of a change and ship it safely across several sites." },
  { number: "03", title: "Revalidation flow", href: "/work/revalidation-flow", eyebrow: "Craft CMS · Next.js caching", intro: "Tracing an issue across Craft events, bulk actions, webhooks and Next.js cache behaviour.", detail: "Content publishing issues rarely live in one layer. I work through the complete path: Craft element events and action behaviour, payload construction, tags and paths, Next.js invalidation and the frontend result — including the awkward cases that only fail during bulk operations or when content is disabled.", result: "Issues are resolved at their actual cause, not hidden behind another workaround." },
];

export default function Home() {
  const [open, setOpen] = useState<number | null>(0);
  const [menu, setMenu] = useState(false);
  const [headerHidden, setHeaderHidden] = useState(false);
  const [headerFloating, setHeaderFloating] = useState(false);
  useEffect(() => { let last = scrollY, up = 0, down = 0, raf = 0; const update = () => { raf = 0; const current = scrollY, delta = current - last; last = current; setHeaderFloating(current >= 80); if (current < 80) { up = down = 0; setHeaderHidden(false); return; } if (delta > 0) { down += delta; up = 0; if (down > 18) setHeaderHidden(true); } else if (delta < 0) { up -= delta; down = 0; if (up > 12) setHeaderHidden(false); } }; const onScroll = () => { if (!raf) raf = requestAnimationFrame(update); }; raf = requestAnimationFrame(update); addEventListener("scroll", onScroll, { passive: true }); return () => { removeEventListener("scroll", onScroll); if (raf) cancelAnimationFrame(raf); }; }, []);

  return <main>
    <ScrollChoreography />
    <header className={`fixed top-0 left-0 z-10 flex h-[88px] w-full items-center justify-between border-b border-line px-[3vw] transition-[transform,background-color,box-shadow,backdrop-filter] duration-300 max-[800px]:h-[70px] ${headerHidden && !menu ? "-translate-y-[105%]" : "translate-y-0"} ${headerFloating ? "bg-[#f6f5f1]/95 shadow-[0_1px_0_rgba(24,25,22,.12),0_12px_34px_rgba(24,25,22,.07)] backdrop-blur-[11px]" : "bg-transparent"}`}>
      <a className="interactive-underline text-[19px] font-extrabold tracking-[-.04em]" href="#top">JG<span className="ml-[7px] align-top text-[11px] tracking-[.08em] text-muted">—26</span></a>
      <button className="z-12 hidden border-0 bg-transparent max-[800px]:block" aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? "Close" : "Menu"}</button>
      <nav className={`${menu ? "max-[800px]:flex" : "max-[800px]:hidden"} flex gap-8 text-[13px] max-[800px]:fixed max-[800px]:inset-0 max-[800px]:z-11 max-[800px]:flex-col max-[800px]:items-start max-[800px]:justify-center max-[800px]:bg-acid max-[800px]:p-[10vw] max-[800px]:text-[40px]`}>
        {[{ label: "Work", id: "work" }, { label: "Expertise", id: "expertise" }, { label: "How I work", id: "working" }, { label: "About", id: "about" }].map((item) => <a className="interactive-underline" key={item.id} href={`#${item.id}`} onClick={() => setMenu(false)}>{item.label}</a>)}<a className="interactive-underline" href="mailto:hello@javigarcia.dev">Contact ↗</a>
      </nav>
    </header>

    <section className="relative min-h-svh overflow-visible border-b border-line px-[3vw] pt-[145px] pb-[42px] after:pointer-events-none after:absolute after:inset-0 after:z-[1] after:bg-[linear-gradient(90deg,rgba(240,238,232,.92)_0%,rgba(240,238,232,.74)_27%,rgba(240,238,232,.28)_55%,rgba(240,238,232,.04)_78%)] max-[800px]:px-[5vw] max-[800px]:pt-[105px] max-[800px]:pb-[35px] max-[800px]:after:bg-[linear-gradient(180deg,rgba(240,238,232,.62),rgba(240,238,232,.78)_58%,rgba(240,238,232,.94))]" id="top">
      <div className="relative z-[2] flex min-h-[calc(100svh-187px)] w-full flex-col justify-between max-[800px]:min-h-[calc(100svh-140px)]">
        <p className={`${label} intro-reveal`}>Senior React / Next.js developer · Available for agency collaborations</p>
        <h1 className="intro-reveal my-[7vh] max-w-[1050px] text-[clamp(52px,6.75vw,112px)] leading-[.91] font-medium tracking-[-.07em] [animation-delay:.1s] max-[800px]:my-[9vh] max-[800px]:text-[13.8vw]">Senior developer<br />for complex Next.js<br /><em className="inline-block font-serif font-normal transition-[transform,text-shadow] duration-400 hover:[text-shadow:-3px_0_rgba(255,58,118,.52),3px_0_rgba(0,185,255,.52)]">&amp; React</em> projects.</h1>
        <div className="intro-reveal relative z-[2] flex items-end justify-between [animation-delay:.25s]"><p className="ml-[17%] max-w-[560px] text-[17px] leading-[1.45] max-[800px]:ml-0 max-[800px]:max-w-[64%] max-[800px]:text-sm">I help digital agencies with existing, technically demanding web platforms — across Craft CMS, WordPress and other content systems.</p><a className="flex size-[124px] items-end justify-between rounded-full bg-acid p-[21px] text-xs leading-[1.1] transition-all duration-300 hover:rotate-6 hover:scale-106 hover:rounded-[42%_58%_48%_52%] max-[800px]:size-[94px] max-[800px]:p-4" href="#work"><span>Selected<br />work</span><b className="text-[26px] font-normal">↓</b></a></div>
      </div><ThreeNetwork />
    </section>

    <section className={`${section} bg-[linear-gradient(180deg,rgba(240,238,232,.68),rgba(240,238,232,.86)_22%)]`} id="work">
      <div className="scroll-reveal mb-[65px] flex justify-between"><p className={label}>01 / Selected work</p><p className="text-xs text-muted max-[800px]:hidden">Existing platforms. Real constraints. Production work.</p></div>
      {projects.map((project, index) => { const active = open === index; return <article className="border-t border-ink" key={project.title}>
        <button className="scroll-reveal grid w-full cursor-pointer grid-cols-[7%_30%_1fr_40px] items-center border-0 bg-transparent py-[35px] text-left transition-[padding,background-color] duration-300 hover:pl-3 hover:bg-white/20 max-[800px]:grid-cols-[10%_1fr_30px]" style={{ "--delay": `${index * .07}s` } as React.CSSProperties} aria-expanded={active} onClick={() => setOpen(active ? null : index)}>
          <span className="text-[11px] text-muted">{project.number}</span><span><small className={`${smallMeta} mb-2`}>{project.eyebrow}</small><strong className="text-[clamp(34px,5vw,70px)] font-medium tracking-[-.05em]">{project.title}</strong></span><span className="max-w-[470px] text-[15px] leading-[1.45] text-[#50524d] max-[800px]:hidden">{project.intro}</span><span className={`inline-flex size-10 items-center justify-center justify-self-end text-[30px] leading-none transition-transform duration-300 ${active ? "rotate-180" : "group-hover:rotate-90"}`}>{active ? "−" : "+"}</span>
        </button>
        <div className={`grid transition-[grid-template-rows,opacity] duration-500 ${active ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"}`} aria-hidden={!active}><div className="grid min-h-0 grid-cols-[55%_minmax(0,1fr)] gap-[6%] overflow-hidden max-[800px]:grid-cols-1">
          <div className="relative mb-[60px] min-h-[390px] overflow-hidden bg-[#20221e] max-[800px]:mb-[35px] max-[800px]:min-h-[260px]"><div className="absolute top-[10%] left-[16%] h-[63%] w-[72%] -rotate-5 border border-[#85887b] bg-[#d9d8d0] p-[22px] text-[10px] tracking-[.12em] uppercase shadow-[0_20px_60px_#0006]">system / context / delivery</div><div className="absolute top-[22%] left-[19%] flex h-[64%] w-[72%] rotate-4 justify-between border border-[#85887b] bg-[#d9d8d0] p-[22px] shadow-[0_20px_60px_#0006]"><b className="text-[34px] tracking-[-.06em] lowercase">{index === 0 ? "morae" : "next"}</b><i className="h-[70%] w-[42%] rounded-[50%_50%_40%_60%] bg-acid" /></div></div>
          <div className="mb-[60px] flex flex-col justify-between text-lg leading-[1.6] max-[800px]:mb-[35px] max-[800px]:gap-[35px] max-[800px]:text-base"><p>{project.detail}</p><div><p className="border-t border-line pt-5 text-sm"><small className={`${smallMeta} mb-2.5`}>What this demonstrates</small>{project.result}</p><Link className="interactive-underline mt-[22px] flex justify-between overflow-hidden border-t border-ink py-[15px] text-xs tracking-[.1em] uppercase" href={project.href}>View full case study <span className="text-lg transition-transform duration-300 group-hover:translate-x-1">↗</span></Link></div></div>
        </div></div>
      </article>; })}
    </section>

    <section className={section} id="expertise"><p className={`${label} scroll-reveal`}>02 / What I can help with</p><p className="scroll-reveal my-[80px] mr-0 mb-[110px] ml-[17%] max-w-[1180px] text-[clamp(33px,5vw,74px)] leading-[1.04] tracking-[-.05em] max-[800px]:my-[60px] max-[800px]:mb-[75px] max-[800px]:ml-0">Bring me into the project when the platform is <span className="highlight-sweep">already live, already complex</span> and the team needs useful output — not another onboarding problem.</p><div className="ml-[17%] grid grid-cols-2 border-t border-l border-ink max-[800px]:ml-0 max-[800px]:grid-cols-1">{[["01", "Extra senior capacity", "Join an agency team for a demanding delivery phase, backlog or deadline and start contributing inside the existing workflow."], ["02", "Complex issue resolution", "Trace problems across React, Next.js, APIs, CMS integrations, caching, previews, redirects and content workflows until the real cause is found."], ["03", "Platform evolution", "Refactor, migrate or extend mature systems — whether they use Craft, WordPress or another CMS — without ignoring their technical and editorial history."], ["04", "Frontend architecture", "Build reusable React systems that remain understandable when multiple sites, content types and developers are involved."]].map((item, index) => <article className="scroll-reveal flex min-h-[255px] flex-col border-r border-b border-line px-7 py-6 hover:-translate-y-[3px] hover:bg-white/25 max-[800px]:min-h-[220px]" style={{ "--delay": `${index * .08}s` } as React.CSSProperties} key={item[0]}><small className="text-[10px] text-muted">{item[0]}</small><h3 className="mt-auto mb-[22px] text-[clamp(26px,3vw,44px)] font-medium tracking-[-.045em]">{item[1]}</h3><p className="max-w-[430px] text-sm leading-[1.55] text-[#50524d]">{item[2]}</p></article>)}</div></section>

    <section className={section} id="working"><p className={`${label} scroll-reveal`}>03 / How I work</p><div className="scroll-reveal my-[75px] mr-0 mb-[105px] ml-[17%] grid grid-cols-[1.25fr_.75fr] items-end gap-[8%] max-[800px]:my-[60px] max-[800px]:mb-[75px] max-[800px]:ml-0 max-[800px]:grid-cols-1 max-[800px]:gap-[45px]"><h2 className="text-[clamp(52px,7vw,104px)] leading-[.88] font-medium tracking-[-.065em]">Useful from<br /><em className="font-serif font-normal">day zero.</em></h2><p className="text-[17px] leading-[1.55]">Agencies rarely need another developer who can only be productive after the difficult decisions have already been made. They need someone who can enter the middle of the story, understand what is there and move it forward.</p></div><div className="ml-[17%] border-t border-ink max-[800px]:ml-0">{[["01", "Read the system", "I map the architecture, conventions and immediate risk before changing code."], ["02", "Join the team", "I work with the existing people, tools and delivery process rather than creating a parallel universe."], ["03", "Resolve and ship", "I take ownership of issues, communicate trade-offs and deliver production-ready work."]].map((item, index) => <p className="scroll-reveal grid grid-cols-[8%_1fr] border-b border-line py-7 max-[800px]:grid-cols-[12%_1fr]" style={{ "--delay": `${index * .08}s` } as React.CSSProperties} key={item[0]}><b className="text-[10px] text-muted">{item[0]}</b><span className="grid grid-cols-[32%_1fr] gap-[6%] text-sm leading-normal transition-transform duration-300 hover:translate-x-2 max-[800px]:grid-cols-1 max-[800px]:gap-3"><strong className="text-xl font-medium">{item[1]}</strong>{item[2]}</span></p>)}</div></section>

    <section className={`${section} grid grid-cols-[17%_1fr] max-[800px]:grid-cols-1 max-[800px]:gap-[50px]`} id="about"><p className={`${label} scroll-reveal`}>04 / Experience</p><div className="scroll-reveal grid grid-cols-[1.5fr_1fr_1fr] gap-[5%] max-[800px]:grid-cols-1 max-[800px]:gap-[30px]"><h2 className="text-[clamp(44px,6vw,88px)] leading-[.95] font-medium tracking-[-.06em]">Senior judgement.<br /><em className="font-serif font-normal">Hands-on delivery.</em></h2><p className="mt-2 leading-[1.6]">I am Javi Garcia, a senior frontend developer specialising in React and Next.js, with deep experience integrating content platforms including Craft CMS and WordPress. My strongest work happens where understanding the existing system matters as much as writing the next component.</p><p className="mt-2 leading-[1.6]">I collaborate with digital agencies as experienced development capacity: joining established teams, taking responsibility for difficult issues and contributing from the first stage of the engagement through to production.</p></div></section>
    <section className="scroll-reveal relative z-[1] flex justify-between gap-[30px] border-b border-line bg-paper/80 px-[3vw] py-[30px] backdrop-blur-[2px] max-[800px]:flex-col max-[800px]:px-[5vw] max-[800px]:py-[26px]"><p className={label}>A flexible senior resource</p><p className="text-xs text-muted max-[800px]:leading-[1.6]">Project rescue · Delivery support · Ongoing platform work · Technical problem solving</p></section>
    <footer className={footer}><p className={label}>Need senior capacity on a demanding platform?</p><a className="my-[70px] mb-[140px] flex justify-between text-[clamp(42px,7.5vw,116px)] leading-none tracking-[-.06em] max-[800px]:my-[60px] max-[800px]:mb-[100px] max-[800px]:leading-[.95]" href="mailto:hello@javigarcia.dev">Let’s talk about the project. <span className="inline-block text-acid transition-transform duration-400 hover:translate-x-[9px] hover:-translate-y-[9px] hover:-rotate-5">↗</span></a><div className="flex justify-between border-t border-[#4e5049] pt-5 text-[11px] tracking-[.1em] uppercase"><span>Javi Garcia © 2026</span><span className="max-[800px]:hidden">Next.js · React · CMS platforms</span><a className="interactive-underline" href="#top">Back to top ↑</a></div></footer>
  </main>;
}
